### PR TITLE
Use cql2-json for pgstac

### LINKED ISSUE #511: cql2 filter issues
I was experimenting with using `stac-rs` as a STAC API server for a pgstac database and I ran into some issues when using the `filter` parameter.

When I run a query against a `stac-fastapi-pgstac` API, I get the expected result:
```python
import httpx

get_params = { 
    "collection": "noaa-hrrr-conus-sfc", 
    "filter": "forecast:horizon = 'PT1H'",
}

get_stacfastapi_pgstac = httpx.get(
    "http://localhost:8081/search",
    params=get_params
)

for item in get_stacfastapi_pgstac.json()["features"]:
    print(item["id"])
```
```
hrrr-conus-sfc-2024-08-15T23-FH1
hrrr-conus-sfc-2024-08-15T22-FH1
hrrr-conus-sfc-2024-08-15T21-FH1
hrrr-conus-sfc-2024-08-15T20-FH1
hrrr-conus-sfc-2024-08-15T19-FH1
hrrr-conus-sfc-2024-08-15T18-FH1
hrrr-conus-sfc-2024-08-15T17-FH1
hrrr-conus-sfc-2024-08-15T16-FH1
hrrr-conus-sfc-2024-08-15T15-FH1
hrrr-conus-sfc-2024-08-15T14-FH1
```

When I run the same query against the `stac-rs` API (started with `stacrs serve --pgstac postgresql://username:password@localhost:5439/postgis --verbose` I get a database error:
```python
get_stacrs = httpx.get(
    "http://localhost:7822/search",
    params=get_params,
)
```
```
> 'db error: ERROR: invalid input syntax for type boolean: "forecast:horizon = \'PT1H\'"'
```

It seems like something is going wrong when translating the cql2-text for `pgstac`.

I tried a similar test with a POST request but it looks like POST requests to `/search` are not yet implemented.

Here is a sample item collection with two items with different values for the `forecast:horizon` parameter in case that is helpful context.
[item_collection.json](https://github.com/user-attachments/files/17605034/item_collection.json)

### PR DESCRIPTION
**Pull request by gadomski**
@hrodmn can you try out this branch on your side? **pgstac** doesn't accept `cql2-text` AFAICT so I added an auto-conversion to `cql2-json`.

## Closes

- Closes #511

Includes a sidecar `stacrs pgstac load` command.

### CODE REVIEW

**Comment by hrodmn** [comment]
@gadomski thanks for taking a look! I am having trouble setting up a local installation of this branch (see details below), but I think your diagnosis of the problem is correct. In stac-fastapi-pgstac all GET requests with `cql2-text` filters get converted to `cql2-json` before they are passed to the `pgstac` search function.

<details><summary>installation error</summary>
<p>
Sadly I don't know where to start on this error :laughing:

```shell
henry@quercus:~/workspace/stac-utils/stac-rs/python$ uv sync
Resolved 142 packages in 3ms
error: Failed to prepare distributions
  Caused by: Failed to build `stacrs @ file:///home/henry/workspace/stac-utils/stac-rs/python`
  Caused by: Build backend failed to build editable through `build_editable` (exit status: 1)

[stdout]
Running `maturin pep517 build-wheel -i /home/henry/.cache/uv/builds-v0/.tmp4OsYVt/bin/python --compatibility off --editable`

[stderr]
🔗 Found pyo3 bindings
🐍 Found CPython 3.12 at /home/henry/.cache/uv/builds-v0/.tmp4OsYVt/bin/python
📡 Using build options features from pyproject.toml
   Compiling pyo3-build-config v0.22.6
   Compiling geoarrow v0.3.0
   Compiling pyo3-macros-backend v0.22.6
   Compiling pyo3-ffi v0.22.6
   Compiling pyo3 v0.22.6
   Compiling pyo3-macros v0.22.6
   Compiling pythonize v0.22.0
error[E0275]: overflow evaluating the requirement `<impl GeometryTrait<T = f64> as geo_traits::geometry::GeometryTrait>::GeometryCollection<'_>: geo_traits::geometry_collection::GeometryCollectionTrait`
    |
    = help: consider increasing the recursion limit by adding a `#![recursion_limit = "256"]` attribute to your crate (`geoarrow`)
note: required for `GeometryCollectionIterator<'_, f64, <... as GeometryCollectionTrait>::ItemType<'_>, ...>` to implement `Iterator`
   --> /home/henry/.cargo/registry/src/index.crates.io-6f17d22bba15001f/geoarrow-0.3.0/src/geo_traits/iterator.rs:39:15
    |
37  |                   ItemType: 'a + $item_trait<T = T>,
    |                                              ----- unsatisfied trait bound introduced here
38  |                   G: $self_trait<T = T, ItemType<'a> = ItemType>,
39  |               > Iterator for $struct_name<'a, T, ItemType, G>
    |                 ^^^^^^^^     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
109 | / impl_iterator!(
110 | |     GeometryCollectionIterator,
111 | |     GeometryCollectionTrait,
112 | |     GeometryTrait,
113 | |     geometry_unchecked
114 | | );
    | |_- in this macro invocation
    = note: required for `GeometryCollectionIterator<'_, f64, <... as GeometryCollectionTrait>::ItemType<'_>, ...>` to implement `IntoIterator`
    = note: the full name for the type has been written to '/home/henry/workspace/stac-utils/stac-rs/target/release/deps/geoarrow-cd11adfc937de9f7.long-type-10257270469153106537.txt'
    = note: consider using `--verbose` to print the full type name to the console
    = note: the full name for the type has been written to '/home/henry/workspace/stac-utils/stac-rs/target/release/deps/geoarrow-cd11adfc937de9f7.long-type-10257270469153106537.txt'
    = note: consider using `--verbose` to print the full type name to the console
    = note: this error originates in the macro `impl_iterator` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0275`.
error: could not compile `geoarrow` (lib) due to 1 previous error
💥 maturin failed
  Caused by: Failed to build a native library through cargo
  Caused by: Cargo build finished with "exit status: 101": `env -u CARGO PYO3_ENVIRONMENT_SIGNATURE="cpython-3.12-64bit" PYO3_PYTHON="/home/henry/.cache/uv/builds-v0/.tmp4OsYVt/bin/python" PYTHON_SYS_EXECUTABLE="/home/henry/.cache/uv/builds-v0/.tmp4OsYVt/bin/python" "cargo" "rustc" "--features" "pyo3/extension-module" "--message-format" "json-render-diagnostics" "--manifest-path" "/home/henry/workspace/stac-utils/stac-rs/python/Cargo.toml" "--release" "--lib"`
Error: command ['maturin', 'pep517', 'build-wheel', '-i', '/home/henry/.cache/uv/builds-v0/.tmp4OsYVt/bin/python', '--compatibility', 'off', '--editable'] returned non-zero exit status 1

```

</p>
</details>

**Comment by gadomski** [comment]
> I am having trouble setting up a local installation of this branch (see details below)

Try keeping your Rust at 1.81 or below, it's a bug in [geoarrow-rs](https://github.com/geoarrow/geoarrow-rs/issues/833):

```shell
rustup override set 1.81  # to override for your project directory
```

**Comment by hrodmn** [comment]
> Try keeping your Rust at 1.81 or below, it's a bug in [geoarrow-rs](https://github.com/geoarrow/geoarrow-rs/issues/833):
> 
> ```shell
> rustup override set 1.81  # to override for your project directory
> ```
That solved the installation problem!

As far as I can tell the communication with `pgstac` is working correctly now (based on pgstac logs in my docker network) but there is a new error coming from the `stacrs` side (I think). Whenever I provide a `filter` parameter I am getting a 500 response with the text `"unsupported value"`.

I am serving the STAC API with:
```shell
$ cargo run -- serve --pgstac postgresql://username:password@localhost:5439/postgis -v
```

Is there a way to get more verbose logs to help trace the error?

**Comment by gadomski** [comment]
> Is there a way to get more verbose logs to help trace the error?

Yeah, you can provide more `-v`s, e.g. `-vvv` to get full debug logging. You can also set the `RUST_LOG` envvar, e.g.:

```shell
RUST_LOG=stac_server=debug cargo run -- serve
```

Apologies for none of this being documented. Happy to debug on my side as well if you want to provide your example query.

**Comment by hrodmn** [comment]
I am seeing more logs with `-vvv` but I don't see the source of `unsupported value`.

Here is how I am setting up a query in Python (based on the new sentinel-2-l2a items):

```json
import httpx

get_params = {
    "collection": "sentinel-2-l2a",
    "filter": "proj:epsg = 32613",
    "limit": 10,
}

get_stacrs = httpx.get(
    "http://localhost:7822/search",
    params=get_params,
)
```

Here is a plain ol` request URL:
http://localhost:7822/search?collection=sentinel-2-l2a&filter=proj:epsg=32613&limit=10

**Comment by gadomski** [comment]
🙇🏼 thanks so much for kicking the tires here @hrodmn. Turns out I wasn't serializing filters correctly at all, and this helped catch that. Give it another spin — I added a bit more logging and tracing too.

**Comment by gadomski** [comment]
> can we add the filter extension conformance class?

Yup, good call ... I'll do that (and update the README) in another PR.

> would it make sense to add some tests to the server crate or the pgstac crate?

Lol you bet ... there's some, but I hadn't been exercising `filter` at all.

**Pull request merged**
